### ISSUE TITLE
No detection for stalemate

### ISSUE THREAD

**Issue by TheyCallMeTojo** [ScottLilly/MogriChess#27]
In this scenario, once light captured, it left only the dark King. Dark King is not in check, but has no valid moves. This should be detected as a stalemate and game ends in a draw. (Assuming you're following the traditional stalemate rule). 

![Capture](https://user-images.githubusercontent.com/5115817/150700791-8c6fc21f-59a2-40d5-b207-1a8ff01bae8c.PNG)
[gameData.zip](https://github.com/ScottLilly/MogriChess/files/7921589/gameData.zip)

**Comment by ScottLilly** [comment]
Stalemate is definitely something I want to get into version 1.0.

Things like "50 moves" or "keeps repeating the same move" may be put off until a later version.
