### ISSUE TITLE
Possible invalid checkmate logic

### ISSUE THREAD

**Issue by TheyCallMeTojo** [ScottLilly/MogriChess#3]
I'm being kind of rough on the game trying to break it. I can't understand why this is checkmate. Light pawn can not move backwards so Dark King should be allowed to move back, back right or back left without being in check. Haven't seen any code to check for 50 move rule, but even then, pieces were captured every move and that'd be reset. 

![whyCheckmate](https://user-images.githubusercontent.com/5115817/150016779-24191894-33e2-41b3-ba94-01f0c57e2fa9.png)

**Comment by ScottLilly** [comment]
Thanks. I'll use this to build a unit test and see why the program thinks this is checkmate.

That's one task I'm not looking forward to - creating all the potential scenarios.

**Comment by TheyCallMeTojo** [comment]
![StillHasMoves](https://user-images.githubusercontent.com/5115817/150025103-66148ddc-4118-4ed3-85e4-0c7a59b41f5c.png)

**Comment by TheyCallMeTojo** [comment]
![stillhasmoves](https://user-images.githubusercontent.com/5115817/150064403-e50e8927-3719-420d-846b-3ae32cb5e5c2.png)

**Comment by TheyCallMeTojo** [comment]
![stillhavemoves](https://user-images.githubusercontent.com/5115817/150070680-fe9933bf-f949-4819-9b84-35c029afa850.png)

**Comment by ScottLilly** [comment]
NOTE: This may be fixed, but not closing until unit tests are created for the examples attached to this issue.

See ticket: #4
