### ISSUE TITLE
Saving 'current game state' throws exception.

### ISSUE THREAD

**Issue by TheyCallMeTojo** [ScottLilly/MogriChess#61]
Square model isn't properly mapped and causes exception when trying to save Current Game State.
![Screenshot_2](https://user-images.githubusercontent.com/5115817/153269644-89c27f52-101f-4fc4-bb79-057429cc5b30.png)

**Comment by ScottLilly** [comment]
Add unit tests for the BoardStateService functions.

**Comment by ScottLilly** [comment]
Creating unit tests in #62
